import { afterAll, afterEach, beforeAll, describe, expect, it } from "vitest";
import request from "supertest";
import type { Socket } from "socket.io-client";

import app from "../../src/app.js";
import { prisma } from "../../src/lib/prisma.js";
import { REALTIME_EVENTS } from "../../src/realtime/realtime.constants.js";
import { emitToWorkspace } from "../../src/realtime/realtime.emitter.js";

import { resetDatabase } from "../setup/reset-database.js";
import {
  createProjectDirect,
  createSprintDirect,
  createTaskDirect,
  createWorkspaceWithMember,
  signUpTestUser,
} from "../setup/fixtures.js";
import { startTestServer, type TestServer } from "../setup/test-server.js";
import { connectTestSocket, trackEvent, waitForEvent, waitForEventWithRetries } from "../setup/socket-client.js";

// A sentinel event, distinct from ACTIVITY_CREATED, used only to prove a
// socket is connected/joined/still-listening - same role and same choice
// (PROJECT_CREATED) as tests/realtime/workspace-room-isolation.test.ts's own
// CROSS_WORKSPACE_SENTINEL, so a real delivery can never be confused with
// the event actually under test.
const SENTINEL_EVENT = REALTIME_EVENTS.PROJECT_CREATED;

/**
 * Proves the entity mutation and its activity write commit or roll back
 * together, by forcing the *second* write (the Activity insert) to fail
 * after the *first* (the entity write) has already been attempted inside
 * the same transaction - the exact ordering a transaction is supposed to
 * protect against.
 *
 * A JS-level mock on `prisma.activity.create` cannot do this: the `tx`
 * client Prisma hands to a `$transaction` callback is a distinct object
 * from the global `prisma` singleton (verified empirically - patching
 * `prisma.<model>.create` never intercepts a call made through `tx`), so
 * any interception has to happen at the database level to reach a write
 * made via `tx`. A real Postgres trigger does: it fires for every INSERT
 * into "Activity" from any connection, transaction-scoped client included,
 * which is exactly what's needed here. It's scoped to one specific
 * (actorId, ActivityType) pair - known ahead of time from the test's own
 * fixtures - so it can never affect any other activity write, in this file
 * or any other, and is torn down in `finally` regardless of outcome.
 */
async function withActivityInsertFailure(
  actorId: string,
  activityType: string,
  run: () => Promise<void>,
): Promise<void> {
  const suffix = `${Date.now()}_${Math.random().toString(36).slice(2, 8)}`;
  const functionName = `test_reject_activity_fn_${suffix}`;
  const triggerName = `test_reject_activity_trigger_${suffix}`;

  // actorId is a cuid generated by our own fixtures (signUpTestUser), never
  // user input, and activityType is always one of this file's own literal
  // call-site arguments below - both safe to interpolate directly, matching
  // the same non-parameterized $executeRawUnsafe usage already established
  // in tests/setup/reset-database.ts for the same reason (DDL identifiers
  // and enum literals can't be bound as query parameters anyway).
  await prisma.$executeRawUnsafe(`
    CREATE OR REPLACE FUNCTION "${functionName}"() RETURNS trigger AS $$
    BEGIN
      IF NEW."actorId" = '${actorId}' AND NEW."type" = '${activityType}'::"ActivityType" THEN
        RAISE EXCEPTION 'test-injected activity insert failure';
      END IF;
      RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;
  `);

  await prisma.$executeRawUnsafe(`
    CREATE TRIGGER "${triggerName}"
    BEFORE INSERT ON "Activity"
    FOR EACH ROW EXECUTE FUNCTION "${functionName}"();
  `);

  try {
    await run();
  } finally {
    await prisma.$executeRawUnsafe(`DROP TRIGGER IF EXISTS "${triggerName}" ON "Activity";`);
    await prisma.$executeRawUnsafe(`DROP FUNCTION IF EXISTS "${functionName}"();`);
  }
}

describe("entity + activity writes are transactional", () => {
  let testServer: TestServer;
  const openSockets: Socket[] = [];

  beforeAll(async () => {
    testServer = await startTestServer();
  });

  afterAll(async () => {
    await testServer.close();
  });

  afterEach(async () => {
    openSockets.forEach((socket) => socket.disconnect());
    openSockets.length = 0;

    await resetDatabase();
  });

  it("rolls back task creation when its activity write fails, leaving neither the task nor the activity persisted", async () => {
    const owner = await signUpTestUser(app);
    const { workspace } = await createWorkspaceWithMember(owner.userId);
    const project = await createProjectDirect(workspace.id, owner.userId);

    const taskTitle = `Rollback probe ${Date.now()}`;

    await withActivityInsertFailure(owner.userId, "TASK_CREATED", async () => {
      const res = await request(app)
        .post(`/api/v1/projects/${project.id}/tasks`)
        .set("Cookie", owner.cookie)
        .send({ title: taskTitle });

      expect(res.status).toBeGreaterThanOrEqual(500);
      expect(res.body.success).toBe(false);
    });

    const persistedTask = await prisma.task.findFirst({
      where: { projectId: project.id, title: taskTitle },
    });
    expect(persistedTask).toBeNull();

    const persistedActivity = await prisma.activity.findFirst({
      where: { workspaceId: workspace.id, type: "TASK_CREATED" },
    });
    expect(persistedActivity).toBeNull();
  });

  it("rolls back a sprint-task assignment when its activity write fails, leaving the task unassigned and no activity persisted", async () => {
    const owner = await signUpTestUser(app);
    const { workspace } = await createWorkspaceWithMember(owner.userId);
    const project = await createProjectDirect(workspace.id, owner.userId);
    const task = await createTaskDirect(workspace.id, project.id, owner.userId);
    const sprint = await createSprintDirect(workspace.id, project.id);

    await withActivityInsertFailure(
      owner.userId,
      "TASK_ASSIGNED_TO_SPRINT",
      async () => {
        const res = await request(app)
          .post(`/api/v1/sprints/${sprint.id}/tasks/${task.id}`)
          .set("Cookie", owner.cookie)
          .send();

        expect(res.status).toBeGreaterThanOrEqual(500);
        expect(res.body.success).toBe(false);
      },
    );

    const persistedTask = await prisma.task.findUniqueOrThrow({
      where: { id: task.id },
    });
    expect(persistedTask.sprintId).toBeNull();

    const persistedActivity = await prisma.activity.findFirst({
      where: { workspaceId: workspace.id, type: "TASK_ASSIGNED_TO_SPRINT" },
    });
    expect(persistedActivity).toBeNull();
  });

  /**
   * Proves the fix for the realtime-before-commit bug: createActivity(data,
   * tx) used to call emitToWorkspace(ACTIVITY_CREATED, ...) immediately
   * after staging the write inside `tx`, before the surrounding
   * $transaction had actually committed - so a client could be told about
   * an activity whose row then rolled back. createActivity now returns a
   * deferred emit callback instead, and every transactional caller (see
   * task/sprint/sprint-task/project services) only invokes it after
   * $transaction resolves successfully - so a rolled-back transaction must
   * never invoke it at all.
   *
   * A weak version of this test would just spy on emitToWorkspace and
   * assert it wasn't called - but that only proves the function wasn't
   * invoked in-process, not that a real client would never have observed
   * the event. This uses a genuine, connected Socket.IO client (the same
   * infrastructure/pattern as
   * tests/realtime/workspace-room-isolation.test.ts's forbidden/sentinel
   * checks) instead: a listener is registered before the failing request is
   * even sent, and a real, independently-triggered sentinel event on the
   * same socket afterward proves the socket was live and listening for the
   * entire window, not just that nothing happened to arrive yet.
   */
  it("never emits ACTIVITY_CREATED for an activity write that rolled back", async () => {
    const owner = await signUpTestUser(app);
    const { workspace } = await createWorkspaceWithMember(owner.userId);
    const project = await createProjectDirect(workspace.id, owner.userId);

    const socket = await connectTestSocket(testServer.baseUrl, owner.cookie);
    openSockets.push(socket);

    // Confirms the socket has actually joined the workspace room before the
    // real check below - see waitForEventWithRetries's own comment for why
    // a fresh connection can't assume its room join has landed yet.
    await waitForEventWithRetries(socket, SENTINEL_EVENT, () =>
      emitToWorkspace(workspace.id, SENTINEL_EVENT, { marker: "confirm-joined" }),
    );

    const forbidden = trackEvent(socket, REALTIME_EVENTS.ACTIVITY_CREATED);

    const taskTitle = `Realtime rollback probe ${Date.now()}`;

    await withActivityInsertFailure(owner.userId, "TASK_CREATED", async () => {
      const res = await request(app)
        .post(`/api/v1/projects/${project.id}/tasks`)
        .set("Cookie", owner.cookie)
        .send({ title: taskTitle });

      expect(res.status).toBeGreaterThanOrEqual(500);
      expect(res.body.success).toBe(false);
    });

    // The liveness proof described above: a genuine, independently-emitted
    // event on this same socket, after the failing request has already
    // fully resolved, must still arrive - if it didn't, "forbidden was
    // never received" would be meaningless (the socket could just be dead).
    emitToWorkspace(workspace.id, SENTINEL_EVENT, { marker: "liveness-check" });
    await waitForEvent(socket, SENTINEL_EVENT);

    expect(forbidden.wasReceived()).toBe(false);
    forbidden.stop();

    const persistedActivity = await prisma.activity.findFirst({
      where: { workspaceId: workspace.id, type: "TASK_CREATED" },
    });
    expect(persistedActivity).toBeNull();
  });
});
