import { afterEach, describe, expect, it } from "vitest";
import request from "supertest";

import app from "../../src/app.js";
import { prisma } from "../../src/lib/prisma.js";

import { resetDatabase } from "../setup/reset-database.js";
import {
  createProjectDirect,
  createSprintDirect,
  createTaskDirect,
  createWorkspaceWithMember,
  signUpTestUser,
} from "../setup/fixtures.js";

/**
 * Proves the entity mutation and its activity write commit or roll back
 * together, by forcing the *second* write (the Activity insert) to fail
 * after the *first* (the entity write) has already been attempted inside
 * the same transaction - the exact ordering a transaction is supposed to
 * protect against.
 *
 * A JS-level mock on `prisma.activity.create` cannot do this: the `tx`
 * client Prisma hands to a `$transaction` callback is a distinct object
 * from the global `prisma` singleton (verified empirically - patching
 * `prisma.<model>.create` never intercepts a call made through `tx`), so
 * any interception has to happen at the database level to reach a write
 * made via `tx`. A real Postgres trigger does: it fires for every INSERT
 * into "Activity" from any connection, transaction-scoped client included,
 * which is exactly what's needed here. It's scoped to one specific
 * (actorId, ActivityType) pair - known ahead of time from the test's own
 * fixtures - so it can never affect any other activity write, in this file
 * or any other, and is torn down in `finally` regardless of outcome.
 */
async function withActivityInsertFailure(
  actorId: string,
  activityType: string,
  run: () => Promise<void>,
): Promise<void> {
  const suffix = `${Date.now()}_${Math.random().toString(36).slice(2, 8)}`;
  const functionName = `test_reject_activity_fn_${suffix}`;
  const triggerName = `test_reject_activity_trigger_${suffix}`;

  // actorId is a cuid generated by our own fixtures (signUpTestUser), never
  // user input, and activityType is always one of this file's own literal
  // call-site arguments below - both safe to interpolate directly, matching
  // the same non-parameterized $executeRawUnsafe usage already established
  // in tests/setup/reset-database.ts for the same reason (DDL identifiers
  // and enum literals can't be bound as query parameters anyway).
  await prisma.$executeRawUnsafe(`
    CREATE OR REPLACE FUNCTION "${functionName}"() RETURNS trigger AS $$
    BEGIN
      IF NEW."actorId" = '${actorId}' AND NEW."type" = '${activityType}'::"ActivityType" THEN
        RAISE EXCEPTION 'test-injected activity insert failure';
      END IF;
      RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;
  `);

  await prisma.$executeRawUnsafe(`
    CREATE TRIGGER "${triggerName}"
    BEFORE INSERT ON "Activity"
    FOR EACH ROW EXECUTE FUNCTION "${functionName}"();
  `);

  try {
    await run();
  } finally {
    await prisma.$executeRawUnsafe(`DROP TRIGGER IF EXISTS "${triggerName}" ON "Activity";`);
    await prisma.$executeRawUnsafe(`DROP FUNCTION IF EXISTS "${functionName}"();`);
  }
}

describe("entity + activity writes are transactional", () => {
  afterEach(async () => {
    await resetDatabase();
  });

  it("rolls back task creation when its activity write fails, leaving neither the task nor the activity persisted", async () => {
    const owner = await signUpTestUser(app);
    const { workspace } = await createWorkspaceWithMember(owner.userId);
    const project = await createProjectDirect(workspace.id, owner.userId);

    const taskTitle = `Rollback probe ${Date.now()}`;

    await withActivityInsertFailure(owner.userId, "TASK_CREATED", async () => {
      const res = await request(app)
        .post(`/api/v1/projects/${project.id}/tasks`)
        .set("Cookie", owner.cookie)
        .send({ title: taskTitle });

      expect(res.status).toBeGreaterThanOrEqual(500);
      expect(res.body.success).toBe(false);
    });

    const persistedTask = await prisma.task.findFirst({
      where: { projectId: project.id, title: taskTitle },
    });
    expect(persistedTask).toBeNull();

    const persistedActivity = await prisma.activity.findFirst({
      where: { workspaceId: workspace.id, type: "TASK_CREATED" },
    });
    expect(persistedActivity).toBeNull();
  });

  it("rolls back a sprint-task assignment when its activity write fails, leaving the task unassigned and no activity persisted", async () => {
    const owner = await signUpTestUser(app);
    const { workspace } = await createWorkspaceWithMember(owner.userId);
    const project = await createProjectDirect(workspace.id, owner.userId);
    const task = await createTaskDirect(workspace.id, project.id, owner.userId);
    const sprint = await createSprintDirect(workspace.id, project.id);

    await withActivityInsertFailure(
      owner.userId,
      "TASK_ASSIGNED_TO_SPRINT",
      async () => {
        const res = await request(app)
          .post(`/api/v1/sprints/${sprint.id}/tasks/${task.id}`)
          .set("Cookie", owner.cookie)
          .send();

        expect(res.status).toBeGreaterThanOrEqual(500);
        expect(res.body.success).toBe(false);
      },
    );

    const persistedTask = await prisma.task.findUniqueOrThrow({
      where: { id: task.id },
    });
    expect(persistedTask.sprintId).toBeNull();

    const persistedActivity = await prisma.activity.findFirst({
      where: { workspaceId: workspace.id, type: "TASK_ASSIGNED_TO_SPRINT" },
    });
    expect(persistedActivity).toBeNull();
  });
});
